#include "framework.hpp"
#include "stream_builder.hpp"

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iterator>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include "btrfs/send.hpp"

//The fixture tests read the streams generated by tests/integration/gen-fixtures.sh. The directory is passed
//in by CMake so the tests do not depend on the fixtures being copied next to the binary.
#ifndef BTRFS_SEND_PARSER_FIXTURE_DIR
#define BTRFS_SEND_PARSER_FIXTURE_DIR "."
#endif

using namespace btrfs::send;
using testfw::StreamBuilder;
using protocol::Attribute;
using protocol::Command;

namespace {

const Uuid kUuidA = testfw::make_uuid(0xaa);

void put_subvol(StreamBuilder& builder, std::string_view path = "subvol")
{
    builder.begin_command(Command::Subvol);
    builder.put_string(Attribute::Path, path);
    builder.put_uuid(Attribute::Uuid, kUuidA);
    builder.put_u64(Attribute::CtransId, 7);
    builder.end_command();
}

void put_end(StreamBuilder& builder)
{
    builder.begin_command(Command::End);
    builder.end_command();
}

//A stream whose commands and attributes straddle chunk boundaries wherever the chunk size puts them.
StreamBuilder make_large_stream(std::uint32_t version = 2)
{
    StreamBuilder builder(version);
    put_subvol(builder, "subvol");
    for (std::uint64_t index = 0; index < 4; ++index)
    {
        std::string data;
        data.reserve(5001);
        for (std::size_t byte = 0; byte < 5001; ++byte)
            data.push_back(static_cast<char>('a' + ((byte + index) % 26)));
        builder.begin_command(Command::Write);
        builder.put_string(Attribute::Path, "file-" + std::to_string(index) + ".bin");
        builder.put_u64(Attribute::FileOffset, index * 4096);
        builder.put_bytes(Attribute::Data, data);
        builder.end_command();
    }
    put_end(builder);
    return builder;
}

std::string read_fixture(const std::string& name)
{
    std::ifstream file(std::string(BTRFS_SEND_PARSER_FIXTURE_DIR) + "/" + name, std::ios::binary);
    return std::string(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>());
}

struct ParseOutcome
{
    bool failed = false;
    ErrorCode code = ErrorCode::InvalidStreamHeader;
    std::vector<std::string> summaries;
};

//Parses bytes that are handed out at most chunk bytes at a time, through the non-throwing API so a failure is
//reported instead of ending the case early.
ParseOutcome parse_with_chunk(const std::string& bytes, std::size_t chunk)
{
    ParseOutcome outcome;
    MemorySource memory(bytes);
    ChunkedSource chunked(memory, chunk);
    Parser parser(chunked);
    SendOperation operation;
    ParseFailure failure;

    for (;;)
    {
        const NextStatus status = parser.next(operation, failure);
        if (status == NextStatus::EndOfStream)
            break;
        if (status == NextStatus::Error)
        {
            outcome.failed = true;
            outcome.code = failure.code;
            break;
        }
        outcome.summaries.push_back(summary(operation));
    }
    return outcome;
}

std::vector<std::string> summaries_of(const std::string& bytes)
{
    MemorySource source(bytes);
    const SendStream stream = parse(source);
    std::vector<std::string> result;
    result.reserve(stream.operations.size());
    for (const SendOperation& operation : stream.operations)
        result.push_back(summary(operation));
    return result;
}

//Hands out one byte at a time no matter how much is asked for.
class OneByteSource final : public ByteSource
{
public:
    explicit OneByteSource(std::string bytes)
        : m_Bytes(std::move(bytes))
    {
    }

    std::size_t read(std::byte* out, std::size_t size) override
    {
        if (size == 0 || m_Position == m_Bytes.size())
            return 0;
        *out = static_cast<std::byte>(static_cast<unsigned char>(m_Bytes[m_Position]));
        m_Position += 1;
        return 1;
    }

private:
    std::string m_Bytes;
    std::size_t m_Position = 0;
};

//Delivers a prefix of the stream and then end of input, forever.
class StallingSource final : public ByteSource
{
public:
    StallingSource(std::string bytes, std::size_t delivered)
        : m_Bytes(std::move(bytes))
        , m_Delivered(std::min(delivered, m_Bytes.size()))
    {
    }

    std::size_t read(std::byte* out, std::size_t size) override
    {
        if (size == 0 || m_Position == m_Delivered)
            return 0;
        const std::size_t count = std::min(size, m_Delivered - m_Position);
        std::memcpy(out, m_Bytes.data() + m_Position, count);
        m_Position += count;
        return count;
    }

private:
    std::string m_Bytes;
    std::size_t m_Delivered;
    std::size_t m_Position = 0;
};

//Delivers some bytes and then throws, the way a pipe whose writer died or a disk that disappeared behaves.
class FailingAfterSource final : public ByteSource
{
public:
    FailingAfterSource(std::string bytes, std::size_t delivered)
        : m_Bytes(std::move(bytes))
        , m_Delivered(std::min(delivered, m_Bytes.size()))
    {
    }

    std::size_t read(std::byte* out, std::size_t size) override
    {
        if (size == 0)
            return 0;
        if (m_Position == m_Delivered)
            throw std::runtime_error("connection reset by peer");
        const std::size_t count = std::min(size, m_Delivered - m_Position);
        std::memcpy(out, m_Bytes.data() + m_Position, count);
        m_Position += count;
        return count;
    }

private:
    std::string m_Bytes;
    std::size_t m_Delivered;
    std::size_t m_Position = 0;
};

//Claims to have stored more bytes than it was asked for, which is a bug in a source and not end of input.
class OverreportingSource final : public ByteSource
{
public:
    explicit OverreportingSource(std::string bytes)
        : m_Bytes(std::move(bytes))
    {
    }

    std::size_t read(std::byte* out, std::size_t size) override
    {
        const std::size_t count = std::min(size, m_Bytes.size() - m_Position);
        std::memcpy(out, m_Bytes.data() + m_Position, count);
        m_Position += count;
        return count + 1;
    }

private:
    std::string m_Bytes;
    std::size_t m_Position = 0;
};

const std::size_t kChunkSizes[] = {1, 2, 3, 5, 7, 11, 13, 64, 999, 4096};

}

TEST_CASE(short_reads_do_not_change_the_result)
{
    const std::string bytes = make_large_stream(2).bytes();
    const std::vector<std::string> expected = summaries_of(bytes);
    CHECK_EQ(expected.size(), std::size_t(6));

    for (const std::size_t chunk : kChunkSizes)
    {
        const ParseOutcome outcome = parse_with_chunk(bytes, chunk);
        CHECK_MSG(!outcome.failed, "chunk size " + std::to_string(chunk));
        CHECK_MSG(outcome.summaries == expected, "chunk size " + std::to_string(chunk));
    }
}

TEST_CASE(a_source_may_return_a_single_byte_per_read)
{
    const StreamBuilder builder = make_large_stream(1);
    OneByteSource source(builder.bytes());
    const SendStream stream = parse(source);

    CHECK_EQ(stream.count(Command::Write), std::size_t(4));
    const std::vector<const WriteOperation*> writes = stream.of_type<WriteOperation>();
    for (std::size_t index = 0; index < writes.size(); ++index)
    {
        CHECK_EQ(writes[index]->data.size(), std::size_t(5001));
        CHECK_EQ(writes[index]->file_offset, static_cast<std::uint64_t>(index) * 4096);
        CHECK_EQ(static_cast<char>(*writes[index]->data.data()), static_cast<char>('a' + index));
    }
}

TEST_CASE(chunked_source_reports_its_limit)
{
    const std::string bytes = make_large_stream(1).bytes();
    MemorySource memory(bytes);

    ChunkedSource limited(memory, 3);
    CHECK_EQ(limited.max_chunk(), std::size_t(3));

    MemorySource other(bytes);
    //A zero chunk would never make progress, so it is clamped to one byte.
    ChunkedSource clamped(other, 0);
    CHECK_EQ(clamped.max_chunk(), std::size_t(1));
}

TEST_CASE(real_fixture_read_one_byte_at_a_time)
{
    const std::string bytes = read_fixture("full-v1.bin");
    CHECK(!bytes.empty());

    const std::vector<std::string> expected = summaries_of(bytes);
    const ParseOutcome outcome = parse_with_chunk(bytes, 1);
    CHECK(!outcome.failed);
    CHECK_EQ(outcome.summaries, expected);
    CHECK_EQ(expected.size(), std::size_t(118));
}

TEST_CASE(truncated_input_fails_or_yields_a_prefix)
{
    const std::string bytes = make_large_stream(2).bytes();
    const std::vector<std::string> expected = summaries_of(bytes);
    std::size_t failures = 0;
    std::size_t prefixes = 0;

    for (const std::size_t chunk : {std::size_t(1), std::size_t(3), std::size_t(17)})
    {
        for (std::size_t length = 1; length < bytes.size(); ++length)
        {
            const ParseOutcome outcome = parse_with_chunk(bytes.substr(0, length), chunk);
            if (outcome.failed)
            {
                ++failures;
                continue;
            }
            //A clean result is only acceptable on a command boundary, and then it has to be a prefix of the
            //full stream: a truncation must never invent or reorder operations.
            ++prefixes;
            CHECK(outcome.summaries.size() <= expected.size());
            CHECK(std::equal(outcome.summaries.begin(), outcome.summaries.end(), expected.begin()));
        }
    }

    //Both outcomes have to actually happen, otherwise this case proves nothing.
    CHECK(failures > 0);
    CHECK(prefixes > 0);

    //Cutting the last byte off has to fail: it truncates the checksum field of the END command.
    const ParseOutcome cut = parse_with_chunk(bytes.substr(0, bytes.size() - 1), 1);
    CHECK(cut.failed);
    CHECK_EQ(cut.code, ErrorCode::UnexpectedEndOfStream);
}

TEST_CASE(a_stalling_source_is_a_short_stream_not_a_loop)
{
    const std::string bytes = make_large_stream(1).bytes();

    //Inside the stream header.
    {
        MemorySource memory("");
        StallingSource source(bytes, 5);
        Parser parser(source);
        CHECK_PARSE_ERROR(parser.next(), ErrorCode::InvalidStreamHeader);
    }

    //Inside a command header.
    {
        StallingSource source(bytes, protocol::kStreamHeaderSize + 4);
        Parser parser(source);
        SendOperation operation;
        ParseFailure failure;
        CHECK_EQ(parser.next(operation, failure), NextStatus::Error);
        CHECK_EQ(failure.code, ErrorCode::UnexpectedEndOfStream);
        CHECK(failure.message.find("command header") != std::string::npos);
    }

    //Inside the payload of the first command.
    {
        StallingSource source(bytes, protocol::kStreamHeaderSize + protocol::kCommandHeaderSize + 10);
        Parser parser(source);
        CHECK_PARSE_ERROR(parser.next(), ErrorCode::UnexpectedEndOfStream);
    }

    //At a command boundary the same source ends the stream cleanly.
    {
        StreamBuilder builder(1);
        put_subvol(builder);
        put_end(builder);
        const std::string small = builder.bytes();
        StallingSource source(small, small.size());
        const SendStream stream = parse(source);
        CHECK_EQ(stream.operations.size(), std::size_t(2));
    }
}

TEST_CASE(an_empty_source_reports_an_empty_stream)
{
    StallingSource source("", 0);
    Parser parser(source);
    CHECK_PARSE_ERROR(parser.next(), ErrorCode::InvalidStreamHeader);

    //Zero sized reads must not be mistaken for end of input either.
    StreamBuilder builder(1);
    put_subvol(builder);
    put_end(builder);
    OneByteSource one_byte(builder.bytes());
    const SendStream stream = parse(one_byte);
    CHECK_EQ(stream.operations.size(), std::size_t(2));
}

TEST_CASE(a_source_that_overreports_is_rejected)
{
    OverreportingSource source(make_large_stream(1).bytes());
    Parser parser(source);
    CHECK_PARSE_ERROR(parser.next(), ErrorCode::SourceReadFailed);

    //The failure is a source problem, not a truncated stream, so the caller can tell them apart.
    OverreportingSource other(make_large_stream(1).bytes());
    Parser second_parser(other);
    SendOperation operation;
    ParseFailure failure;
    CHECK_EQ(second_parser.next(operation, failure), NextStatus::Error);
    CHECK(failure.message.find("more bytes than requested") != std::string::npos);
}

TEST_CASE(a_source_failure_midway_is_reported_with_its_offset)
{
    const std::string bytes = make_large_stream(2).bytes();
    const std::size_t delivered = protocol::kStreamHeaderSize + protocol::kCommandHeaderSize + 2000;

    FailingAfterSource source(bytes, delivered);
    Parser parser(source);
    SendOperation operation;
    ParseFailure failure;

    //The first command is complete, so it arrives before the failure.
    CHECK_EQ(parser.next(operation, failure), NextStatus::HaveOperation);
    CHECK(operation.is<SubvolOperation>());

    CHECK_EQ(parser.next(operation, failure), NextStatus::Error);
    CHECK_EQ(failure.code, ErrorCode::SourceReadFailed);
    CHECK_EQ(failure.stream_offset, static_cast<std::uint64_t>(delivered));
    CHECK_EQ(failure.command_index, std::uint64_t(2));
    CHECK(failure.message.find("connection reset by peer") != std::string::npos);

    //A source error is terminal, later calls must not try to read again.
    CHECK_EQ(parser.next(operation, failure), NextStatus::EndOfStream);
}

TEST_CASE(chunked_sources_nest)
{
    const std::string bytes = make_large_stream(2).bytes();
    MemorySource memory(bytes);
    ChunkedSource outer(memory, 3);
    ChunkedSource inner(outer, 2);
    CHECK_EQ(inner.max_chunk(), std::size_t(2));

    const SendStream stream = parse(inner);
    CHECK_EQ(stream.count(Command::Write), std::size_t(4));
    CHECK_EQ(stream.count(Command::End), std::size_t(1));
}
